export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const FAILED_LOGIN = 'FAILED_LOGIN';


